//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string avatar { get; set; }
        public Nullable<byte> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string hobbies { get; set; }
        public string description { get; set; }
        public string passWord { get; set; }
        public Nullable<byte> isAdministrator { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string updateBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    }
}
