//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> producerID { get; set; }
        public string name { get; set; }
        public string avatar { get; set; }
        public Nullable<decimal> price { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyWord { get; set; }
        public string MetaDescription { get; set; }
        public string slug { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string updateBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    }
}
